name: FuxelSagt
main: FuxelSagt
authors: [ AzraAnimating, Snocember, Joshua5e0, Kara ]
description: ''

version: 1.0
api-version: '1.20'

commands:
  testcommand:
    description: 'testcommand'
  teststart:
  configure:
    aliases: [ configure, einstellungen, settings ]